services:
  db:
    image: mysql:8
    container_name: mysql-db
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - app-network

  microservice:
    image: microservice-mysql-springdatajpa:latest
    container_name: ms-mysql-springdatajpa
    env_file: .env
    environment:
      MYSQL_HOST: db
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
